import { CardInfoVi } from './cardDataVi';

export interface ExpansionCard extends CardInfoVi {
  expansion: string;
  imagePath: string;
}

export const expansionCards: ExpansionCard[] = [

  {
    "name": "+2/-2 BaN Modifier",
    "nameVi": "Lá bài Bổ Trợ +2/-2 Tấn Công",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau kết quả đổ xúc xắc bất kỳ. Cộng 2 hoặc trừ 2 vào kết quả đó. Nếu bạn đang Tấn Công Quái Vật, cộng thêm 4 vào kết quả đó thay thế.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/+2-2BaNModifier.webp"
  },
  {
    "name": "+7 BaN Modifier",
    "nameVi": "Lá bài Bổ Trợ +7 & Bỏ Bài",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau kết quả đổ xúc xắc bất kỳ. Bỏ toàn bộ bài trên tay của bạn và cộng thêm 7 vào kết quả đổ đó.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/+7BaNModifier.webp"
  },
  {
    "name": "Annihilator",
    "nameVi": "Kẻ Hủy Diệt Annihilator",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "6+",
    "effectVi": "Tìm một lá bài Thử thách (Challenge card) trong chồng bài bỏ và thêm nó vào tay bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/annihilator.webp"
  },
  {
    "name": "Bark Hexer",
    "nameVi": "Kẻ Nguyền Rủa Vỏ Cây",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "7+",
    "effectVi": "BỎ 1 lá bài. Mỗi người chơi khác phải BỎ 2 lá bài.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/barkHexer.webp"
  },
  {
    "name": "Beholden Retriever",
    "nameVi": "Chó Săn Hồn",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "5+",
    "effectVi": "HIẾN TẾ một lá bài Anh hùng. Tìm một lá bài Anh hùng hoặc Vật phẩm trong chồng bài loại và thêm nó vào tay bạn, sau đó chơi lá bài đó ngay lập tức.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/beholdenRetriever.webp"
  },
  {
    "name": "Berserker Challenge",
    "nameVi": "Thách Thức Cuồng Chiến",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/berserkerChallenge.webp"
  },
  {
    "name": "Berserker Mask",
    "nameVi": "Mặt Nạ Cuồng Chiến",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Anh Hùng được trang bị lá bài này sẽ được tính thuộc lớp nhân vật Cuồng Chiến (Berserker) thay vì lớp nhân vật gốc.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/berserkerMask.webp"
  },
  {
    "name": "Biggest Ring Ever",
    "nameVi": "Nhẫn Lớn Nhất Lịch Sử",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Mỗi khi bạn đổ xúc xắc kích hoạt kỹ năng của Anh Hùng được trang bị, bạn được phép bỏ tối đa 3 lá bài trên tay. Với mỗi lá bỏ đi, cộng thêm 2 vào kết quả đổ đó.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/biggestRingEver.webp"
  },
  {
    "name": "Bone Collector",
    "nameVi": "Kẻ Thu Thập Xương",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "7+",
    "effectVi": "HIẾN TẾ một lá bài Vật phẩm. Tìm một lá bài Anh hùng trong chồng bài loại và thêm nó vào tay bạn, sau đó chơi lá bài đó ngay lập tức.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/boneCollector.webp"
  },
  {
    "name": "Boston Terror",
    "nameVi": "Quái Vật Boston Terror",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "7+",
    "effectVi": "Chọn một người chơi. Người chơi đó có thể đưa cho bạn một lá bài từ tay họ. Nếu họ không làm vậy, bạn có thể chọn 2 lá bài từ chồng bài bỏ và thêm chúng vào tay bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/bostonTerror.webp"
  },
  {
    "name": "Brawling Spirit",
    "nameVi": "Linh Hồn Quyết Chiến",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "9+",
    "effectVi": "Mỗi người chơi (bao gồm cả bạn) có hơn 3 lá bài trong Đội của họ phải HIẾN TẾ một lá bài.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/brawlingSpirit.webp"
  },
  {
    "name": "Dragon's Bile",
    "nameVi": "Mật Rồng Độc Dược",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Nếu bạn kích hoạt thất bại kỹ năng của Anh Hùng được trang bị, bạn buộc phải HY SINH 1 lá bài Anh Hùng trong tổ đội.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/dragonsBile.webp"
  },
  {
    "name": "Goblet of Caffeination",
    "nameVi": "Chén Tỉnh Táo Caffein",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Nếu bạn kích hoạt thất bại kỹ năng của Anh Hùng được trang bị, bạn có thể HY SINH lá bài Vật Phẩm này để lập tức đổ xúc xắc kích hoạt lại kỹ năng đó.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/gobletOfCaffeination.webp"
  },
  {
    "name": "Grim Pupper",
    "nameVi": "Chó Thần Chết Grim Pupper",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "8+",
    "effectVi": "Mỗi người chơi (bao gồm cả bạn) phải HIẾN TẾ (SACRIFICE) một lá bài.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/grimPupper.webp"
  },
  {
    "name": "Gruesome Gladiator",
    "nameVi": "Đấu Sĩ Tàn Bạo",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "10+",
    "effectVi": "Xem bài trên tay của mỗi người chơi khác. Chọn một lá bài từ tay mỗi người chơi đó và thêm vào tay của bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/gruesomeGladiator.webp"
  },
  {
    "name": "Hollow Husk",
    "nameVi": "Xác Rỗng Hollow Husk",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "6+",
    "effectVi": "Xem tay của một người chơi khác. Chọn một lá bài Phép thuật (nếu họ có) và thêm nó vào tay bạn. Bạn có thể chơi nó ngay lập tức.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/hollowHusk.webp"
  },
  {
    "name": "Lightning Labrys",
    "nameVi": "Rìu Chiến Sấm Sét Labrys",
    "type": "magic",
    "typeVi": "Phép Thuật",
    "class": "magic",
    "classVi": "Phép Thuật",
    "effectVi": "Bỏ tối đa 3 lá bài trên tay. Với mỗi lá bỏ đi, chọn một người chơi khác và buộc họ phải HY SINH 1 lá Anh Hùng.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/lightningLabrys.webp"
  },
  {
    "name": "Mass Sacrifice",
    "nameVi": "Hiến Tế Hàng Loạt",
    "type": "magic",
    "typeVi": "Phép Thuật",
    "class": "magic",
    "classVi": "Phép Thuật",
    "effectVi": "Bỏ toàn bộ các lá bài trên tay của bạn, sau đó RÚT ngay 5 lá bài mới.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/massSacrifice.webp"
  },
  {
    "name": "Meowntain",
    "nameVi": "Mèo Khổng Lồ Meowntain",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "6+",
    "effectVi": "HIẾN TẾ một lá bài. Cộng +5 vào tất cả các lần đổ xúc xắc của bạn cho đến cuối lượt.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/meowntain.webp"
  },
  {
    "name": "Necromancer Challenge",
    "nameVi": "Thách Thức Gọi Hồn",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/necromancerChallenge.webp"
  },
  {
    "name": "Necromancer Mask",
    "nameVi": "Mặt Nạ Pháp Sư Gọi Hồn",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Anh Hùng được trang bị lá bài này sẽ được tính thuộc lớp nhân vật Pháp Sư Gọi Hồn (Necromancer) thay vì lớp nhân vật gốc.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/necromancerMask.webp"
  },
  {
    "name": "Perfect Vessel",
    "nameVi": "Vật Chủ Hoàn Hảo",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "4+",
    "effectVi": "HIẾN TẾ lá bài này, sau đó TRỘM một lá bài Anh hùng.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/perfectVessel.webp"
  },
  {
    "name": "Rabid Beast",
    "nameVi": "Dã Thú Điên Cuồng",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "6+",
    "effectVi": "HIẾN TẾ bất kỳ số lượng lá bài nào, sau đó PHÁ HỦY số lượng lá bài tương đương.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/rabidBeast.webp"
  },
  {
    "name": "Roaryal Guard",
    "nameVi": "Hộ Vệ Hoàng Gia Roaryal",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "9+",
    "effectVi": "Chọn một Lớp (Class). Trả lại mọi lá bài Anh hùng thuộc Lớp đó về tay của người chơi tương ứng.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/roaryalGuard.webp"
  },
  {
    "name": "Shadow Saint",
    "nameVi": "Thánh Nhân Bóng Tối",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Necromancer",
    "rollReq": "5+",
    "effectVi": "BỎ một lá bài Điều chỉnh (Modifier card). Không người chơi nào khác có thể chơi các lá bài Điều chỉnh cho đến hết lượt của bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/shadowSaint.webp"
  },
  {
    "name": "Silver Lining",
    "nameVi": "Tia Hy Vọng Bạc",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Nếu bạn kích hoạt thất bại kỹ năng của Anh Hùng được trang bị, cộng thêm 2 vào tất cả các lượt đổ xúc xắc của bạn trong lượt này.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/silverLining.webp"
  },
  {
    "name": "Soulbound Grimoire",
    "nameVi": "Sách Phép Ràng Buộc Linh Hồn",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Mỗi lần bạn đổ xúc xắc kích hoạt kỹ năng của Anh Hùng được trang bị sẽ tiêu tốn 2 Điểm Hành Động (AP) thay vì 1 AP.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/soulboundGrimoire.webp"
  },
  {
    "name": "Unbridled Fury",
    "nameVi": "Cơn Thịnh Nộ Không Kiểm Soát",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "8+",
    "effectVi": "PHÁ HỦY một lá bài Anh hùng. Nếu lá bài Anh hùng đó là Berserker, bạn có thể dành thêm một điểm hành động trong lượt này.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/unbridledFury.webp"
  },
  {
    "name": "Vicious Wildcat",
    "nameVi": "Mèo Rừng Hung Dữ",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Berserker",
    "rollReq": "12+",
    "effectVi": "TIÊU DIỆT bất kỳ lá bài Quái vật nào, sau đó kết thúc lượt của bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Cards/viciousWildcat.webp"
  },
  {
    "name": "Gnawing Dread",
    "nameVi": "Thủ Lĩnh Nỗi Sợ Gặm Nhấm",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "necromancer",
    "classVi": "Thủ Lĩnh Necromancer",
    "effectVi": "Mỗi lượt một lần trong lượt của bạn, bạn có thể dành 2 điểm hành động để tìm trong chồng bài bỏ một lá bài và thêm nó vào tay bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Leaders/gnawingDread.webp"
  },
  {
    "name": "Raging Manticore",
    "nameVi": "Thủ Lĩnh Quái Thú Nhân Sư Phẫn Nộ",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "berserker",
    "classVi": "Thủ Lĩnh Berserker",
    "effectVi": "Mỗi khi bạn TIÊU DIỆT một lá bài Quái vật, RÚT 2 lá bài.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Leaders/ragingManticore.webp"
  },
  {
    "name": "Doombringer",
    "nameVi": "Kẻ Mang Tai Ương",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "8+",
    "failReq": "<4",
    "effectVi": "Thành công: TIÊU DIỆT lá bài Quái vật này.\nThất bại: BỎ tay bài của bạn.\nHiệu ứng: Mỗi khi bạn HIẾN TẾ một lá bài, bạn có thể chọn một lá bài từ chồng bài bỏ và thêm nó vào tay bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Monsters/doombringer.webp"
  },
  {
    "name": "Reptilian Ripper",
    "nameVi": "Thằn Lằn Xé Xác",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "7+",
    "failReq": "<7",
    "effectVi": "Thành công: TIÊU DIỆT lá bài Quái vật này.\nThất bại: HIẾN TẾ 2 lá bài Anh hùng.\nHiệu ứng: Mỗi khi bạn đổ xúc xắc để TẤN CÔNG một lá bài Quái vật, cộng +2 vào kết quả đổ của bạn.",
    "expansion": "BerserkersAndNecromancers",
    "imagePath": "assets/expansion/BerserkersAndNecromancers/Monsters/reptilianRipper.webp"
  },
  {
    "name": "-6 DS Modifier",
    "nameVi": "Lá bài Bổ Trợ -6 & Bỏ 1",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau kết quả đổ xúc xắc bất kỳ. Bỏ đi 1 lá bài trên tay và trừ 6 vào kết quả đổ đó.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/-6DSModifier.webp"
  },
  {
    "name": "+6 DS Modifier",
    "nameVi": "Lá bài Bổ Trợ +6 & Bỏ 1",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau kết quả đổ xúc xắc bất kỳ. Bỏ đi 1 lá bài trên tay và cộng thêm 6 vào kết quả đổ đó.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/+6DSModifier.webp"
  },
  {
    "name": "Dragalter",
    "nameVi": "Rồng Phép Dragalter",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "7+",
    "effectVi": "BỎ một lá bài Điều chỉnh. Bạn có thể áp dụng hiệu ứng của lá bài Điều chỉnh đó cho tất cả các lần đổ xúc xắc của bạn trong phần còn lại của lượt này.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/dragalter.webp"
  },
  {
    "name": "Dystortivern",
    "nameVi": "Rồng Không Gian Distortivern",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "10+",
    "effectVi": "Trao đổi lá bài Thủ lĩnh Đội (Party Leader) với một người chơi khác.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/dystortivern.webp"
  },
  {
    "name": "Egg of Fortune",
    "nameVi": "Quả Trứng May Mắn",
    "type": "magic",
    "typeVi": "Phép Thuật",
    "class": "magic",
    "classVi": "Phép Thuật",
    "effectVi": "BỎ một lá bài, sau đó rút một lá bài từ tay của mỗi người chơi khác.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/eggOfFortune.webp"
  },
  {
    "name": "Extraga",
    "nameVi": "Rồng Nguyên Tố Extraga",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "7+",
    "effectVi": "Mỗi người chơi (bao gồm cả bạn) phải trả lại bất kỳ lá bài Phù thủy nào khác trong Đội của họ về tay của họ.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/extraga.webp"
  },
  {
    "name": "Luut",
    "nameVi": "Rồng Trộm Cắp Luut",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "7+",
    "effectVi": "TRỘM một lá bài Vật phẩm và trang bị nó cho một lá bài Anh hùng trong Đội của bạn.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/luut.webp"
  },
  {
    "name": "Mirroryu",
    "nameVi": "Rồng Gương Mirroryu",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "7+",
    "effectVi": "Đổ xúc xắc để sử dụng hiệu ứng của bất kỳ lá bài Anh hùng nào trong Đội của bạn ngay lập tức. +3 vào kết quả đổ đó.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/mirroryu.webp"
  },
  {
    "name": "Oracon",
    "nameVi": "Rồng Tiên Tri Oracon",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "7+",
    "effectVi": "Lấy một lá bài từ tay người chơi khác. Nếu đó là lá bài Điều chỉnh, người chơi đó phải HIẾN TẾ một lá bài Anh hùng.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/oracon.webp"
  },
  {
    "name": "Renovern",
    "nameVi": "Rồng Tái Sinh Renovern",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "8+",
    "effectVi": "Tìm một lá bài Vật phẩm trong chồng bài bỏ và chơi nó ngay lập tức.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/renovern.webp"
  },
  {
    "name": "Shamanaga",
    "nameVi": "Rồng Shamanaga",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "7+",
    "effectVi": "Chọn một lá bài Anh hùng từ chồng bài bỏ. Đưa lá bài Anh hùng đó vào Đội của bạn, đổ xúc xắc để sử dụng hiệu ứng của nó ngay lập tức, sau đó HIẾN TẾ nó.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/shamanaga.webp"
  },
  {
    "name": "Smok",
    "nameVi": "Rồng Khói Smok",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "sorcerer",
    "classVi": "Sorcerer",
    "rollReq": "8+",
    "effectVi": "RÚT 2 lá bài. Nếu ít nhất một trong số các lá bài đó là lá bài Phép thuật, bạn có thể tiết lộ nó, sau đó dành thêm một điểm hành động trong lượt này.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/smok.webp"
  },
  {
    "name": "Sorcerer Challenge",
    "nameVi": "Thách Thức Pháp Sư Sorcerer",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/sorcererChallenge.webp"
  },
  {
    "name": "Sorcerer Mask",
    "nameVi": "Mặt Nạ Pháp Sư Sorcerer",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Anh Hùng được trang bị lá bài này sẽ được tính thuộc lớp nhân vật Sorcerer thay vì lớp nhân vật gốc.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Cards/sorcererMask.webp"
  },
  {
    "name": "Fearless Flame",
    "nameVi": "Thủ Lĩnh Ngọn Lửa Không Sợ Hãi",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "sorcerer",
    "classVi": "Thủ Lĩnh Sorcerer",
    "effectVi": "Mỗi khi bạn đổ xúc xắc, bạn có thể bỏ 1 lá bài trên tay. Nếu bạn làm vậy, cộng thêm 1 vào kết quả đổ đó.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Leaders/fearlessFlame.webp"
  },
  {
    "name": "Calamity Mongrel",
    "nameVi": "Chó Săn Tai Họa",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "8+",
    "failReq": "<5",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Bỏ 2 lá bài trên tay.\nHiệu ứng: Mỗi khi bạn RÚT một lá Thách Thức (Challenge), bạn có thể bỏ nó và RÚT thêm 2 lá bài.",
    "expansion": "DragonSorcerers",
    "imagePath": "assets/expansion/DragonSorcerers/Monsters/calamityMongrel.webp"
  },
  {
    "name": "+1/-4 KSE Modifier",
    "nameVi": "Lá bài Bổ Trợ +1/-4",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau bất kỳ kết quả đổ xúc xắc nào của người chơi bất kỳ. Cộng 1 hoặc trừ 4 vào kết quả đổ đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/+1-4KSEModifier.webp"
  },
  {
    "name": "+2/-3 KSE Modifier",
    "nameVi": "Lá bài Bổ Trợ +2/-3",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau bất kỳ kết quả đổ xúc xắc nào của người chơi bất kỳ. Cộng 2 hoặc trừ 3 vào kết quả đổ đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/+2-3KSEModifier.webp"
  },
  {
    "name": "+3/-2 KSE Modifier",
    "nameVi": "Lá bài Bổ Trợ +3/-2",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau bất kỳ kết quả đổ xúc xắc nào của người chơi bất kỳ. Cộng 3 hoặc trừ 2 vào kết quả đổ đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/+3-2KSEModifier.webp"
  },
  {
    "name": "+4/-1 KSE Modifier",
    "nameVi": "Lá bài Bổ Trợ +4/-1",
    "type": "modifier",
    "typeVi": "Bổ Trợ",
    "class": "modifier",
    "classVi": "Bổ Trợ",
    "effectVi": "Chơi lá bài này sau bất kỳ kết quả đổ xúc xắc nào của người chơi bất kỳ. Cộng 4 hoặc trừ 1 vào kết quả đổ đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/+4-1KSEModifier.webp"
  },
  {
    "name": "Bard Challenge",
    "nameVi": "Thách Thức Nhạc Sĩ",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/bardChallenge.webp"
  },
  {
    "name": "Bearserker",
    "nameVi": "Gấu Berserker",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "fighter",
    "classVi": "Chiến Binh",
    "rollReq": "6+",
    "effectVi": "Chọn bất kỳ người chơi nào. Người chơi đó phải BỎ tất cả các lá bài trên tay và RÚT 3 lá bài.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/bearserker.webp"
  },
  {
    "name": "Captivating Spell",
    "nameVi": "Bùa Chú Quyến Rũ",
    "type": "magic",
    "typeVi": "Phép Thuật Cường Hóa",
    "class": "magic",
    "classVi": "Phép Thuật",
    "effectVi": "Cộng thêm 3 vào tất cả kết quả đổ xúc xắc của bạn cho tới cuối lượt chơi này.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/captivatingSpell.webp"
  },
  {
    "name": "Complex Illusion",
    "nameVi": "Ảo Ảnh Phức Tạp",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "guardian",
    "classVi": "Hộ Vệ",
    "rollReq": "8+",
    "effectVi": "RÚT 2 lá bài. Nếu ít nhất một trong các lá bài đó là lá bài Điều chỉnh (Modifier card), bạn có thể tiết lộ nó, sau đó dành thêm một điểm hành động trong lượt này.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/complexIllusion.webp"
  },
  {
    "name": "Enchantler",
    "nameVi": "Yêu Tinh Sừng Ma Thuật",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Druid",
    "rollReq": "7-",
    "effectVi": "BỎ bất kỳ số lượng lá bài nào. Cộng +2 vào tất cả các lần đổ xúc xắc của bạn trong phần còn lại của lượt này cho mỗi lá bài đã bỏ.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/enchantler.webp"
  },
  {
    "name": "Fighter Challenge",
    "nameVi": "Thách Thức Chiến Binh",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/fighterChallenge.webp"
  },
  {
    "name": "Guardian Challenge",
    "nameVi": "Thách Thức Hộ Vệ",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/guardianChallenge.webp"
  },
  {
    "name": "Hamlet",
    "nameVi": "Chuột Hamlet",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "bard",
    "classVi": "Nhạc Sĩ",
    "rollReq": "7+",
    "effectVi": "Mỗi người chơi (bao gồm cả bạn) phải trả lại bất kỳ Người hát rong nào khác trong Đội của họ về tay của họ.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/hamlet.webp"
  },
  {
    "name": "Hoodwink",
    "nameVi": "Yêu Tinh Mũ Trùm Hoodwink",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "ranger",
    "classVi": "Cung Thủ",
    "rollReq": "8+",
    "effectVi": "Tráo đổi các lá bài Vật phẩm được trang bị cho bất kỳ 2 lá bài Anh hùng nào.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/hoodwink.webp"
  },
  {
    "name": "Mask of Misfortune",
    "nameVi": "Mặt Nạ Vô Danh Vận Rủi",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Anh Hùng trang bị mặt nạ này sẽ bị mất lớp nhân vật (vô danh/no class).",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/maskOfMisfortune.webp"
  },
  {
    "name": "Mimi",
    "nameVi": "Mèo Mimi Lém Lĩnh",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "wizard",
    "classVi": "Phù Thủy",
    "rollReq": "4+",
    "effectVi": "Chọn một lá bài Anh hùng trong Đội của bất kỳ người chơi nào. Hiệu ứng của Mimi trở thành hiệu ứng của lá bài Anh hùng đó (bao gồm cả chi phí đổ xúc xắc) cho đến cuối lượt của bạn. Bạn có thể đổ xúc xắc để sử dụng hiệu ứng đó ngay lập tức.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/mimi.webp"
  },
  {
    "name": "Mysterious Feather",
    "nameVi": "Lông Vũ Thần Bí",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Mỗi khi bạn đổ xúc xắc kích hoạt kỹ năng của Anh Hùng được trang bị, bạn có thể chọn bỏ 1 lá bài trên tay để cộng thêm 3 vào kết quả đổ.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/mysteriousFeather.webp"
  },
  {
    "name": "Nimble Gray",
    "nameVi": "Sói Xám Nhanh Nhẹn",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "9+",
    "effectVi": "Bạn có thể TẤN CÔNG bất kỳ lá bài Quái vật nào trong lượt này ngay cả khi bạn không đáp ứng yêu cầu về Đội của lá bài đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/nimbleGray.webp"
  },
  {
    "name": "Purring Bandit",
    "nameVi": "Mèo Đạo Tặc Purring",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "thief",
    "classVi": "Sát Thủ",
    "rollReq": "7+",
    "effectVi": "Lấy một lá bài từ tay của mỗi người chơi có số lượng lá bài trên tay nhiều hơn số lượng lá bài trên tay bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/purringBandit.webp"
  },
  {
    "name": "Ranger Challenge",
    "nameVi": "Thách Thức Cung Thủ",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/rangerChallenge.webp"
  },
  {
    "name": "Thief Challenge",
    "nameVi": "Thách Thức Sát Thủ",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/thiefChallenge.webp"
  },
  {
    "name": "Wizard Challenge",
    "nameVi": "Thách Thức Phù Thủy",
    "type": "challenge",
    "typeVi": "Thách Thức",
    "class": "challenge",
    "classVi": "Thách Thức",
    "effectVi": "Bạn có thể chơi lá bài này khi đối thủ chuẩn bị đánh 1 lá Anh Hùng, Vật Phẩm hoặc Phép Thuật. THÁCH THỨC lá bài đó. Cộng thêm 3 vào kết quả đổ xúc xắc thách thức của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Cards/wizardChallenge.webp"
  },
  {
    "name": "Fierce Panguardian",
    "nameVi": "Thủ Lĩnh Vệ Binh Gấu Trúc Quả Cảm",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "fighter",
    "classVi": "Thủ Lĩnh Hộ Vệ/Chiến binh",
    "effectVi": "Đầu lượt của bạn, bạn có thể đổi lớp nhân vật của thẻ Thủ Lĩnh này giữa Chiến Binh (Fighter) và Hộ Vệ (Guardian).\nMỗi khi bạn THÁCH THỨC đối thủ, người chơi đó không thể chơi bài Bổ Trợ (Modifier) cho đến hết lượt đổ đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/IndividualExclusives/fiercePanguardian.webp"
  },
  {
    "name": "Illusive Trickster",
    "nameVi": "Thủ Lĩnh Kẻ Lừa Đảo Vô Hình",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "thief",
    "classVi": "Thủ Lĩnh Sát thủ/Phù thủy",
    "effectVi": "Đầu lượt của bạn, bạn có thể đổi lớp nhân vật của thẻ Thủ Lĩnh này giữa Sát Thủ (Thief) và Phù Thủy (Wizard).\nMỗi lượt một lần, bạn có thể bỏ 1 lá bài Phép Thuật trên tay và RÚT ngay 3 lá bài mới.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/IndividualExclusives/illusiveTrickster.webp"
  },
  {
    "name": "Rhythmic Archer",
    "nameVi": "Thủ Lĩnh Nhịp Điệu Cung Thủ",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "ranger",
    "classVi": "Thủ Lĩnh Nhạc sĩ/Cung thủ",
    "effectVi": "Đầu lượt của bạn, bạn có thể đổi lớp nhân vật của thẻ Thủ Lĩnh này giữa Nhạc Sĩ (Bard) và Cung Thủ (Ranger).\nMỗi khi có người chơi bất kỳ đổ xúc xắc để Tấn Công Quái Vật thất bại, bạn được RÚT ngay 1 lá bài.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/IndividualExclusives/rhythmicArcher.webp"
  },
  {
    "name": "Brutal Blow",
    "nameVi": "Thủ Lĩnh Đòn Đánh Tàn Bạo",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "fighter",
    "classVi": "Thủ Lĩnh Đấu Sĩ/Cung Thủ",
    "effectVi": "Vào đầu lượt của bạn, bạn có thể chuyển đổi lớp của Brutal Blow giữa Đấu Sĩ và Cung Thủ. Mỗi khi bạn PHÁ HỦY một lá bài Anh hùng, RÚT một lá bài.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Leaders/brutalBlow.webp"
  },
  {
    "name": "Mystical Maestro",
    "nameVi": "Thủ Lĩnh Bậc Thầy Thần Bí",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "wizard",
    "classVi": "Thủ Lĩnh Phù Thủy/Nhạc Sĩ",
    "effectVi": "Đầu lượt của bạn, bạn có thể đổi lớp nhân vật của thẻ Thủ Lĩnh này giữa Phù Thủy (Wizard) và Nhạc Sĩ (Bard).\nMỗi khi bạn đổ xúc xắc đạt kết quả 4 hoặc ít hơn (sau khi đã tính bài Bổ Trợ), bạn được RÚT ngay 1 lá bài.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Leaders/mysticalMaestro.webp"
  },
  {
    "name": "Unstable Unicorn",
    "nameVi": "Thủ Lĩnh Kỳ Lân Bất Ổn",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "noclass",
    "classVi": "Thủ Lĩnh Không Lớp Nhân Vật",
    "effectVi": "Kỳ Lân Bất Ổn không có lớp nhân vật. Vào đầu lượt của bạn, bạn có thể chọn 1 thẻ Thủ Lĩnh của đối thủ. Kỹ năng của Kỳ Lân Bất Ổn sẽ trở thành kỹ năng của thẻ Thủ Lĩnh đó cho tới lượt tiếp theo của bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Leaders/unstableUnicorn.webp"
  },
  {
    "name": "Veiled Raider",
    "nameVi": "Thủ Lĩnh Kẻ Cướp Mặt Nạ",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "guardian",
    "classVi": "Thủ lĩnh Hộ vệ/Kẻ trộm",
    "effectVi": "Đầu lượt của bạn, bạn có thể đổi lớp nhân vật của thẻ Thủ Lĩnh này giữa Hộ Vệ (Guardian) và Sát Thủ (Thief).\nMỗi khi bạn đổ xúc xắc đạt kết quả 12 hoặc hơn (bao gồm bài Bổ Trợ), bạn được phép CƯỚP 1 lá Anh Hùng của đối thủ đưa về tổ đội.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/Leaders/veiledRaider.webp"
  },
  {
    "name": "Howl Of The Dead",
    "nameVi": "Tiếng Hú Từ Địa Ngục",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "necromancer",
    "classVi": "Pháp Sư Cổ Đại",
    "rollReq": "7+",
    "effectVi": "BỎ một lá bài Anh hùng hoặc Vật phẩm. Nếu bạn BỎ một lá bài Anh hùng, PHÁ HỦY một lá bài Anh hùng. Nếu bạn BỎ một lá bài Vật phẩm, thêm một lá bài Anh hùng từ chồng bài bỏ vào tay bạn.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/VinylExclusives/howlOfTheDead.webp"
  },
  {
    "name": "Reigning King",
    "nameVi": "Vua Trị Vì",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "berserker",
    "classVi": "Cuồng Bạo",
    "rollReq": "11+",
    "effectVi": "Chọn một Lớp (Class). PHÁ HỦY tất cả các lá bài Anh hùng thuộc Lớp đó.",
    "expansion": "KSE",
    "imagePath": "assets/expansion/KSE/VinylExclusives/reigningKing.webp"
  },
  {
    "name": "Ancient Megashark",
    "nameVi": "Cổ Đại Siêu Cá Mập",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "9+",
    "failReq": "<6",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn đổ xúc xắc để Tấn Công Quái Vật, cộng thêm 1 vào kết quả.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/ancientMegashark.webp"
  },
  {
    "name": "Clawed Nightmare",
    "nameVi": "Cơn Ác Mộng Vuốt Sắc",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "9+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn kết thúc lượt của mình mà không còn bài trên tay, bạn được chọn cướp 2 lá bài ngẫu nhiên từ tay người chơi khác.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/clawedNightmare.webp"
  },
  {
    "name": "Dragon Wasp",
    "nameVi": "Ong Bắp Cày Rồng",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "7+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi một lá Anh Hùng trong tổ đội của bạn bị hy sinh hoặc phá hủy, bạn có thể chọn bỏ 2 lá bài trên tay thay thế.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/dragonWasp.webp"
  },
  {
    "name": "Goretelodont",
    "nameVi": "Heo Rừng Hủy Diệt",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "9+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn kết thúc lượt của mình mà không còn bài trên tay, bạn được RÚT ngay 3 lá bài.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/goretelodont.webp"
  },
  {
    "name": "Lumbering Demon",
    "nameVi": "Quỷ Khổng Lồ Chậm Chạp",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "8+",
    "failReq": "<6",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn chuẩn bị RÚT 1 lá bài, thay vào đó bạn có thể RÚT 2 lá bài rồi BỎ đi 1 lá trên tay.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/lumberingDemon.webp"
  },
  {
    "name": "Possessed Plush",
    "nameVi": "Gấu Bông Bị Nguyền Rủa",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "7+",
    "failReq": "<5",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn chơi một lá bài Thách Thức (Challenge), bạn được RÚT ngay 1 lá bài.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/possessedPlush.webp"
  },
  {
    "name": "Reef Ripper",
    "nameVi": "Quái Vật Rặng San Hô",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "9+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn đổ xúc xắc kích hoạt kỹ năng Anh Hùng thất bại, bạn được RÚT 1 lá bài.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/reefRipper.webp"
  },
  {
    "name": "Saffyre Phoenix",
    "nameVi": "Phượng Hoàng Lửa Xanh",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "13+",
    "failReq": "<9",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi có một lá Anh Hùng trong tổ đội của bạn bị hy sinh hoặc phá hủy, bạn có thể lập tức chơi 1 lá Anh Hùng từ tay xuống bàn chơi.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/saffyrePhoenix.webp"
  },
  {
    "name": "Scavenger Griffin",
    "nameVi": "Điểu Sư Nhặt Rác",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "9+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn kết thúc lượt của mình mà không còn bài trên tay, bạn được phép CƯỚP 1 lá Anh Hùng từ bàn chơi của đối phương đưa về tổ đội của mình.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/scavengerGriffin.webp"
  },
  {
    "name": "Venomous Gemini",
    "nameVi": "Song Tử Độc Dược",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "7+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Lá bài Song Tử Độc Dược này được tính tương đương với 2 lá bài Quái Vật khi tính điều kiện thắng cuộc.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/venomousGemini.webp"
  },
  {
    "name": "Voltclaw Lion",
    "nameVi": "Sư Tử Lôi Trảo",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "8+",
    "failReq": "<5",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn chơi một lá bài Phép Thuật, bạn được RÚT ngay 1 lá bài.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/voltclawLion.webp"
  },
  {
    "name": "Wandering Behemoth",
    "nameVi": "Quái Thú Lang Thang Behemoth",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "10+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi một lá Anh Hùng trong tổ đội của bạn bị hy sinh hoặc phá hủy, bạn được RÚT ngay 1 lá bài.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/wanderingBehemoth.webp"
  },
  {
    "name": "Wicked Sea Serpent",
    "nameVi": "Thủy Quái Biển Sâu",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "7+",
    "failReq": "<5",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi bạn chơi một lá Vật Phẩm (Item), bạn được RÚT ngay 1 lá bài.",
    "expansion": "MonsterExpansion",
    "imagePath": "assets/expansion/MonsterExpansion/wickedSeaSerpent.webp"
  },
  {
    "name": "Agile Dagger",
    "nameVi": "Dao Găm Nhanh Nhẹn",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "7+",
    "effectVi": "Bạn có thể chơi tối đa 2 lá bài Vật phẩm ngay lập tức.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/agileDagger.webp"
  },
  {
    "name": "Big Buckley",
    "nameVi": "Hươu Lớn Buckley",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "8-",
    "effectVi": "TẤN CÔNG một lá bài Quái vật ngay lập tức. (Bạn vẫn phải đáp ứng yêu cầu về Đội của quái vật đó.)",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/bigBuckley.webp"
  },
  {
    "name": "Blinding Blade",
    "nameVi": "Lưỡi Kiếm Chói Lòa",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "8+",
    "effectVi": "Chọn bất kỳ người chơi nào. Trả lại tất cả các lá bài Vật phẩm được trang bị trong Đội của người chơi đó về tay bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/blindingBlade.webp"
  },
  {
    "name": "Bottomless Bag",
    "nameVi": "Túi Không Đáy",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Bạn có thể đổ xúc xắc để sử dụng hiệu ứng của lá bài Anh hùng được trang bị nhiều hơn một lần mỗi lượt, với chi phí là một điểm hành động cho mỗi lần đổ xúc xắc để sử dụng.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/bottomlessBag.webp"
  },
  {
    "name": "Buck Omens",
    "nameVi": "Hươu Điềm Báo",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "6-",
    "effectVi": "Xem tay của một người chơi khác. Chọn một lá bài Anh hùng từ tay họ (nếu họ có) và đưa nó vào Đội của bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/buckOmens.webp"
  },
  {
    "name": "Critical Fang",
    "nameVi": "Nanh Vuốt Chí Mạng",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "9+",
    "effectVi": "Cộng +4 vào các lần đổ xúc xắc của bạn để TẤN CÔNG một lá bài Quái vật cho đến cuối lượt của bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/criticalFang.webp"
  },
  {
    "name": "Cursed Glove",
    "nameVi": "Găng Tay Nguyền Rủa",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Nếu một lá bài Anh hùng khác trong Đội của bạn bị trộm, hãy di chuyển lá bài Anh hùng được trang bị (với Găng tay này) sang Đội của người chơi đã trộm nó.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/cursedGlove.webp"
  },
  {
    "name": "Doe Fallow",
    "nameVi": "Nai Vàng Fallow",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "7-",
    "effectVi": "HIẾN TẾ một lá bài Anh hùng, sau đó RÚT bài cho đến khi bạn có 7 lá bài trên tay.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/doeFallow.webp"
  },
  {
    "name": "Druid Mask",
    "nameVi": "Mặt Nạ Hiền Triết",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Lá bài Anh hùng được trang bị được coi là một Druid thay vì lớp ban đầu của nó.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/druidMask.webp"
  },
  {
    "name": "Even Bigger Ring",
    "nameVi": "Nhẫn Lớn Hơn Nữa",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Mỗi khi bạn đổ xúc xắc để sử dụng hiệu ứng của lá bài Anh hùng được trang bị, cộng +4 vào kết quả đổ đó.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/evenBiggerRing.webp"
  },
  {
    "name": "Glowing Antler",
    "nameVi": "Gạc Sừng Phát Sáng",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "7-",
    "effectVi": "Bạn có thể chơi tối đa 2 lá bài Phép thuật ngay lập tức.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/glowingAntler.webp"
  },
  {
    "name": "Hardened Hunter",
    "nameVi": "Thợ Săn Dày Dạn",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "9+",
    "effectVi": "RÚT một lá bài cho mỗi lá bài Quái vật trong Đội của mỗi người chơi khác.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/hardenedHunter.webp"
  },
  {
    "name": "Looting Lupo",
    "nameVi": "Sói Lupo Trộm Cướp",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "5+",
    "effectVi": "RÚT một lá bài cho mỗi lá bài Vật phẩm được trang bị cho một lá bài Anh hùng trong Đội của bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/lootingLupo.webp"
  },
  {
    "name": "Maegisty",
    "nameVi": "Nai Hoàng Gia Maegisty",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "7-",
    "effectVi": "Cho đến lượt tiếp theo của bạn, nếu một lá bài Anh hùng trong Đội của bạn bị hiến tế hoặc phá hủy, hãy trả lại lá bài đó về tay bạn thay thế.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/maegisty.webp"
  },
  {
    "name": "Magus Moose",
    "nameVi": "Nai Sừng Tấm Pháp Sư",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "5-",
    "effectVi": "Tìm một lá bài Anh hùng trong chồng bài bỏ và thêm nó vào tay bạn, sau đó chơi lá bài đó ngay lập tức.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/magusMoose.webp"
  },
  {
    "name": "Majestelk",
    "nameVi": "Nai Sừng Tấm Kiêu Hãnh",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "7-",
    "effectVi": "HIẾN TẾ một lá bài Anh hùng. Cộng +5 hoặc -5 vào mỗi lần đổ xúc xắc của bạn cho đến lượt tiếp theo.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/majestelk.webp"
  },
  {
    "name": "Silent Shield",
    "nameVi": "Khiên Lặng Lẽ",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "6+",
    "effectVi": "Trong phần còn lại của lượt, nếu bạn HIẾN TẾ hoặc PHÁ HỦY một lá bài Anh hùng, bạn có thể tìm trong chồng bài bỏ một lá bài Anh hùng và thêm nó vào tay bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/silentShield.webp"
  },
  {
    "name": "Soul Tether",
    "nameVi": "Dây Buộc Linh Hồn",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Nếu bất kỳ lá bài Anh hùng nào trong Đội của bạn bị hiến tế hoặc phá hủy, hãy HIẾN TẾ lá bài Anh hùng được trang bị (với lá bài này).",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/soulTether.webp"
  },
  {
    "name": "Stagguard",
    "nameVi": "Hươu Vệ Binh",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "druid",
    "classVi": "Hiền Triết",
    "rollReq": "8-",
    "effectVi": "Không người chơi nào khác có thể chơi lá bài Bổ trợ cho đến hết lượt của bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/stagguard.webp"
  },
  {
    "name": "Temporal Hourglass",
    "nameVi": "Đồng Hồ Cát Thời Gian",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Nếu bạn đổ xúc xắc không thành công để sử dụng hiệu ứng của lá bài Anh hùng được trang bị, bạn có thể dành thêm một điểm hành động trong lượt này.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/temporalHourglass.webp"
  },
  {
    "name": "Tenacious Timber",
    "nameVi": "Chiến Binh Người Cây",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "8+",
    "effectVi": "Với mỗi lá bài Quái vật trong Đội của bạn, TRỘM một lá bài Anh hùng.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/tenaciousTimber.webp"
  },
  {
    "name": "Warrior Mask",
    "nameVi": "Mặt Nạ Đấu Sĩ",
    "type": "item",
    "typeVi": "Vật Phẩm",
    "class": "item",
    "classVi": "Vật Phẩm",
    "effectVi": "Anh Hùng được trang bị lá bài này sẽ được tính thuộc lớp nhân vật Đấu Sĩ (Warrior) thay vì lớp nhân vật gốc.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/warriorMask.webp"
  },
  {
    "name": "Wolfgang Pack",
    "nameVi": "Sói Wolfgang",
    "type": "hero",
    "typeVi": "Anh Hùng",
    "class": "warrior",
    "classVi": "Đấu Sĩ",
    "rollReq": "5+",
    "effectVi": "Với mỗi lá bài Anh hùng khác trong Đội của bạn, cộng +1 vào tất cả các lần đổ xúc xắc của bạn cho đến cuối lượt.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Cards/wolfgangPack.webp"
  },
  {
    "name": "Noble Shaman",
    "nameVi": "Thủ Lĩnh Hiền Triết Cao Quý",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "druid",
    "classVi": "Thủ Lĩnh Hiền Triết",
    "effectVi": "Mỗi lượt một lần trong lượt của mỗi người chơi, bạn có thể chọn đổ xúc xắc của bất kỳ người chơi nào và trừ -1 vào kết quả đó.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Leaders/nobleShaman.webp"
  },
  {
    "name": "Piercing Howl",
    "nameVi": "Thủ Lĩnh Tiếng Hú Xé Gió",
    "type": "leader",
    "typeVi": "Thủ Lĩnh",
    "class": "warrior",
    "classVi": "Thủ Lĩnh Đấu Sĩ",
    "effectVi": "Mỗi khi bạn đổ xúc xắc, cộng thêm 1 vào kết quả đổ với mỗi lá bài Vật Phẩm đang được trang bị cho các Anh Hùng trong Tổ Đội của bạn.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Leaders/piercingHowl.webp"
  },
  {
    "name": "Feral Dragon",
    "nameVi": "Rồng Hoang Dã",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "9+",
    "failReq": "<7",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi khi người chơi bất kỳ hy sinh 1 lá bài, bạn được RÚT 1 lá bài.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Monsters/feralDragon.webp"
  },
  {
    "name": "Muscipula Rex",
    "nameVi": "Quái Thú Bẫy Kẹp Rex",
    "type": "monster",
    "typeVi": "Quái Vật",
    "class": "large",
    "classVi": "Quái Vật",
    "rollReq": "10+",
    "failReq": "<8",
    "effectVi": "Thành công: Tiêu diệt Quái Vật này.\nThất bại: Phải hy sinh 1 Anh Hùng.\nHiệu ứng: Mỗi lượt một lần trong lượt của bạn, bạn có thể RÚT một lá bài mà không tốn điểm hành động.",
    "expansion": "WarriorsAndDruids",
    "imagePath": "assets/expansion/WarriorsAndDruids/Monsters/muscipulaRex.webp"
  }

];
